-- ===========================================================================
--  TakaBridge - Oracle Database 21c Express Edition schema
--  ---------------------------------------------------------------------
--  EASIEST WAY TO RUN THIS: double click setup-database.bat in this folder.
--  It opens SQL*Plus, asks for your Oracle password once, and runs
--  everything below from top to bottom.
--
--  To run it by hand instead, open SQL*Plus and log in as SYSTEM, then:
--      @C:\path\to\schema.sql
--
--  Run it ONCE. Running it a second time reports "user already exists"
--  and "name is already used by an existing object", which is harmless
--  but means nothing new was created.
-- ===========================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON

PROMPT
PROMPT ====================================================
PROMPT  Step 1 of 3 - creating the takabridge database user
PROMPT ====================================================

-- XEPDB1 is the pluggable database that Oracle XE creates for applications.
-- The SYSTEM account starts off in the container root, so we move into it.
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER takabridge IDENTIFIED BY takabridge123;

-- CONNECT lets the user log in; RESOURCE lets it create its own tables.
GRANT CONNECT, RESOURCE TO takabridge;

-- RESOURCE alone grants no storage, so the user needs a quota as well.
ALTER USER takabridge QUOTA UNLIMITED ON USERS;


PROMPT
PROMPT ====================================================
PROMPT  Step 2 of 3 - creating the tables
PROMPT ====================================================

-- Everything from here on is owned by takabridge, not by SYSTEM.
CONNECT takabridge/takabridge123@localhost:1521/XEPDB1

-- ---------------------------------------------------------------------------
--  Table 1 : CURRENCIES
--  One row per supported currency. rate_per_usd = how many units of this
--  currency equal 1 US Dollar. USD itself is therefore exactly 1.
--  New currencies can be supported later by simply INSERTing another row.
-- ---------------------------------------------------------------------------
CREATE TABLE currencies (
    currency_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          CHAR(3)       NOT NULL UNIQUE,
    name          VARCHAR2(50)  NOT NULL,
    symbol        VARCHAR2(8),
    rate_per_usd  NUMBER(18,6)  NOT NULL,
    updated_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT chk_rate_positive CHECK (rate_per_usd > 0)
);

-- ---------------------------------------------------------------------------
--  Table 2 : CONVERSION_HISTORY
--  One row per successful conversion. Rows belong to a browser session,
--  so no login is required and every visitor sees only their own history.
-- ---------------------------------------------------------------------------
CREATE TABLE conversion_history (
    history_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  VARCHAR2(64)  NOT NULL,
    from_code   CHAR(3)       NOT NULL,
    to_code     CHAR(3)       NOT NULL,
    amount      NUMBER(18,4)  NOT NULL,
    converted   NUMBER(18,4)  NOT NULL,
    rate_used   NUMBER(18,6)  NOT NULL,
    created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_hist_from FOREIGN KEY (from_code) REFERENCES currencies (code),
    CONSTRAINT fk_hist_to   FOREIGN KEY (to_code)   REFERENCES currencies (code)
);

-- Makes "newest 5 rows for this visitor" fast.
CREATE INDEX idx_hist_session_time
    ON conversion_history (session_id, created_at DESC);


PROMPT
PROMPT ====================================================
PROMPT  Step 3 of 3 - inserting the 23 currencies
PROMPT ====================================================

-- ---------------------------------------------------------------------------
--  UNISTR() is used for non-English symbols so this file stays plain ASCII
--  and cannot be corrupted by the Windows console code page.
-- ---------------------------------------------------------------------------
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('BDT', 'Bangladeshi Taka',   UNISTR('\09F3'), 122.000000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('USD', 'US Dollar',          '$',               1.000000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('EUR', 'Euro',               UNISTR('\20AC'),   0.920000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('GBP', 'British Pound',      UNISTR('\00A3'),   0.790000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('INR', 'Indian Rupee',       UNISTR('\20B9'),  88.500000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('JPY', 'Japanese Yen',       UNISTR('\00A5'), 151.200000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('CNY', 'Chinese Yuan',       UNISTR('\00A5'),   7.120000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('AUD', 'Australian Dollar',  'A$',              1.520000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('CAD', 'Canadian Dollar',    'C$',              1.380000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('CHF', 'Swiss Franc',        'CHF',             0.880000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('SGD', 'Singapore Dollar',   'S$',              1.340000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('HKD', 'Hong Kong Dollar',   'HK$',             7.810000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('NZD', 'New Zealand Dollar', 'NZ$',             1.660000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('AED', 'UAE Dirham',         'AED',             3.672500);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('SAR', 'Saudi Riyal',        'SAR',             3.750000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('MYR', 'Malaysian Ringgit',  'RM',              4.450000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('THB', 'Thai Baht',          UNISTR('\0E3F'),  34.200000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('KRW', 'South Korean Won',   UNISTR('\20A9'), 1345.000000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('TRY', 'Turkish Lira',       UNISTR('\20BA'),  34.800000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('SEK', 'Swedish Krona',      'kr',             10.550000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('NOK', 'Norwegian Krone',    'kr',             10.850000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('DKK', 'Danish Krone',       'kr',              6.860000);
INSERT INTO currencies (code, name, symbol, rate_per_usd) VALUES ('ZAR', 'South African Rand', 'R',              18.200000);

COMMIT;


PROMPT
PROMPT ====================================================
PROMPT  Done. The number below must be 23.
PROMPT ====================================================

SELECT COUNT(*) AS currency_count FROM currencies;

EXIT
